---
- name: "Force gathering facts"
  hosts: all
  gather_facts: True
  roles: []

- name: "Converge"
  hosts: gitlab
  become: True
  become_method: sudo
  roles:
    - role: ansible-role-gitlab
  vars:
    molecule_test: True
