---
- name: "Load a variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: "Become section"
  block:
    - name: "Install requirements"
      package:
        name: "{{ package }}"
        state: "present"
      loop: "{{ requirements }}"
      loop_control:
        loop_var: package
  become: True
