---
- name: "Force gathering facts"
  hosts: all
  gather_facts: True
  roles: []

- name: "Converge"
  hosts: gitlab
  become: True
  roles:
    - role: lean_delivery.gitlab
  vars:
    molecule_test: True
